### ISSUE TITLE
Remove logger

### ISSUE THREAD

**Issue by frank-inserve** [GerroDen/vue2-product-fruits#1]
Is it possible you can delete all the console.debugs?

console.debug(`product fruits mounted with ${JSON.stringify(this.$props)}`); 

This reports to much information in production :)

**Comment by PouleR** [comment]
@GerroDen Would you like to remove the console logs from this package? Or if you need a PR that's also fine, I could make one. Would be nice if we can get rid of these messages!

**Comment by GerroDen** [comment]
Hi @PouleR @frank-inserve I removed any `console` commands. :)

**Comment by PouleR** [comment]
Thank you for your quick action, much appreciated!
